services:
  # minio:
  #   image: minio/minio
  #   entrypoint: [""]
  #   command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
  #   environment:
  #     - MINIO_ROOT_USER=mimir
  #     - MINIO_ROOT_PASSWORD=supersecret
  #   volumes:
  #     - minio-data:/data
  tempo:
    image: grafana/tempo:2.7.1
    user: root
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./backends/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/data/tempo
    ports:
      - "14268:14268"   # jaeger ingest
      - "3200:3200"     # tempo
      - "4317:4317"     # otlp grpc
      - "4318:4318"     # otlp http
      - "9411:9411"     # zipkin
      - "6831:6831"     # jaeger thrift_compact

  mimir:
    image: grafana/mimir:latest
    command:
      - --config.file=/etc/mimir/mimir.yaml
    volumes:
      - mimir-data:/data
      - ./backends/mimir:/etc/mimir
    # environment:
    #   - JAEGER_AGENT_HOST=tempo
    #   - JAEGER_AGENT_PORT=6831
    #   - JAEGER_TAGS=app=mimir
    #   - JAEGER_SAMPLER_TYPE=const
    #   - JAEGER_SAMPLER_PARAM=100
    ports:
      - "8080:8080"
      - "9009:9009"
      - "9090:9090"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    volumes:
      - pyroscope-data:/data
    #  - ./backends/pyroscope:/etc/pyroscope

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/data
      - --stability.level=public-preview
      - /etc/alloy/config.alloy
    volumes:
      - alloy-data:/data
      - ./backends/alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345" # HTTP server (UI)
    depends_on:
      - mimir
      - tempo
      - pyroscope

#  k6-tracing:
#    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
#    environment:
#      - ENDPOINT=tempo:4317
#    restart: always
#    depends_on:
#      - tempo

  grafana:
    image: grafana/grafana
    volumes:
     - ./backends/grafana/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoServiceGraph,tempoApmTable,traceqlEditor,metricsSummary
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app,grafana-llm-app




    ports:
      - "10000:3000"
    depends_on:
      - mimir
      - tempo
      - pyroscope

  llm-backend:
    build:
      context: ./llm-backend
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=true
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - llm-backend
  client:
    build:
      context: ./client-simple
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - server

volumes:
  mimir-data:
  alloy-data:
  pyroscope-data:
  tempo-data:
