apiVersion: 1

datasources:
  - uid: pyroscope
    type: grafana-pyroscope-datasource
    name: Pyroscope
    url: http://pyroscope:4040
    access: proxy
    editable: true

  - uid: tempo
    type: tempo
    name: Tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Latency'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
          - name: Request rate
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))'
          - name: Error rate
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags, status_code="STATUS_CODE_ERROR"}[5m]))'
          - name: Duration p99
            query: 'histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le))'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
      exemplars:
        datasourceUid: 'prometheus'
      tracesToProfiles:
        enabled: true
        datasourceUid: 'pyroscope'
        profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
        customQuery: true
        query: 'method="$${__span.tags.method}"'
      spanBar:
        type: 'Tag'
        tag: 'http.path'
      streamingEnabled:
        search: true

  - uid: prometheus
    name: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      alertmanagerUid: "alertmanager"

  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    url: http://mimir:9009/alertmanager
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "cortex"
    secureJsonData:
      httpHeaderValue1: "demo"

